TABLE_MINIMUM = 1
TABLE_MAXIMUM = 5000

PLAYER_STAKE = 10000
PLAYER_ROUNDS = 250

#ROULETTE PLAYERS
RANDOM_BET_AMOUNT = 10 
MARTINGALE_BET_AMOUNT = 10
SEVEN_REDS_BET_AMOUNT = 1500
ROULETTE_1326_BET_AMOUNT = 10

FIBONACCI_PREVIOUS = 0
FIBONACCI_CURRENT = 1

CANCELLATION_SEQ_START = 1
CANCELLATION_SEQ_END = 7

#CRAPS BETTING STRATEGY
NOCHANGE_BETTING_AMOUNT = 10
MARTINGALE_BETTING_AMOUNT = 10
BET1326_BETTING_AMOUNT = 10
